### ISSUE TITLE
the property only loads when copied to puppet/property

### ISSUE THREAD

**Issue by swygue-zz** [voxpupuli/puppet-boolean#1]
I'm using https://github.com/stbenjam/puppet-authconfig which requires puppet-boolean. I've loaded puppet-boolean on the puppetmaster under the modepath folder.

On the client I get this error when I run puppet agent --test.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/authconfig: no such file to load -- puppet/property/boolean on node server2.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

I end up coping the boolean.rb to /usr/lib/ruby/site_ruby/1.8/puppet/property/, now when I run puppet agent --test, it works as expected.

My puppet agent and puppetmaster are both version 3.1.0.

You can ping swygue on irc if you want to chat.

**Comment by bastelfreak** [comment]
as per discussion in https://github.com/voxpupuli/puppet-boolean/issues/34, I'm going to archive this module
