### ISSUE TITLE
release with "v"

### ISSUE THREAD

**Issue by ralfbosz** [voxpupuli/puppet-boolean#30]
The metadata.json is set to "1.1.0"

but the release in GitHub is made as "v1.1.0"

maybe only optical, but seems confusing...

**Comment by ekohl** [comment]
Personally I don't like the ```v``` prefix since I don't see a benefit for it, but it's configured like that for all modules. I think that https://github.com/voxpupuli/modulesync_config is a better place to discuss any change. That's how we create the skeleton around releases for all modules.

**Comment by ralfbosz** [comment]
I'm not proposing a change (which would be welcome, since I also dislike the v), but just pointing to the inconsistency  by a difference in the metadata.json and the release as published on GitHub.

**Comment by ekohl** [comment]
The metadata can't include the ```v``` prefix so I don't think we can fix this.

**Comment by ralfbosz** [comment]
I see, didn't notice it before, but more modules are doing this, still confusing, but ok...

**Comment by ekohl** [comment]
A few years ago someone said prefixing with ```v``` is a good practice and many copied it. Like you I disagree with it but this is the world we live in now.
