### ISSUE TITLE
usage still required with future parser?

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-boolean#7]
Is this really needed when using the future parser and new type system?

**Comment by adrienthebo** [comment]
If Puppet types can use the type system for checking in params then it's not necessary, otherwise it's still needed. If you want to remove the dependency then feel free to copy the rope checking into the param validate functions.

**Comment by bastelfreak** [comment]
as per discussion in https://github.com/voxpupuli/puppet-boolean/issues/34, I'm going to archive this module
