### ISSUE TITLE
Migrate to vox pupuli?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-boolean#8]
Hi @adrienthebo,

Are you interested in migrating the module to Vox Pupuli? We already manage the awesome filemapper and network module, and we would like to spend some love to this one as well.

**Comment by adrienthebo** [comment]
Sure!

**Comment by bastelfreak** [comment]
Hi, I gave you the perms to migrate the module. The steps are documented here: https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

you can ping me or anybody else in #voxpupuli 24/7 on freenode if you've any questions.

**Comment by adrienthebo** [comment]
So I'm incredibly lazy, would you be willing to help with some of the module changes for the 999 version release?

**Comment by bastelfreak** [comment]
yeah sure (I just never did that)! Do you want to come to our IRC channel? I guess that would be the easiest way.

**Comment by igalic** [comment]
now that this is moved, it would be cool to get a release out

**Comment by alexjfisher** [comment]
Released today.
